version: '3'
 
services:
  quyen-golang:
    networks:
      - quyen-network
    external_links:
      - mysql
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ${EGOPATH}:${EGOPATH}
    working_dir: ${EGOPATH}
    security_opt:
      - seccomp:unconfined
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        gopath: ${EGOPATH}

networks: 
  quyen-network:
    external: true
