#!/bin/bash

# Usage:
# - goto_container container_name [bash|sh]

if [ -z $1 ]; then
    echo Missing container name
    exit 1
fi

command=/bin/bash
if [ ! -z $2 ]; then
    command=$2
fi

echo "Goto container $1"
docker exec -ti $1 $command -c "export COLUMNS=`tput cols`; export LINES=`tput lines`; exec $command"
